>general
#BEGIN_VARIABLES
int PRECURSOR_MIN 40
int PRECURSOR_MAX 1200
bool PRINT_PRECURSORS YES
bool EXHAUSTIVE YES
bool SKIP_MT NO
#END_VARIABLES

#BEGIN_COLORS
PF00590 #B3E5B4
NMT_1 #2D8630
NMT_2 #2D8630
BorosinMT #2D8630
PF07746 #B3C6E5
BBD_A #0D47A1
BBD_B #0D47A1
BBD_C #0D47A1
BBD_old #0D47A1
BoroLegA #F9DCB1
BoroLegB #F9DCB1
Boro_6_8 #C552C1
#END_COLORS
>>